# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'OvergateExportApp.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from LogRetrieve import LogRetrieve


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setWindowModality(QtCore.Qt.WindowModal)
        Dialog.setEnabled(True)
        Dialog.resize(451, 241)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        Dialog.setMinimumSize(QtCore.QSize(451, 241))
        Dialog.setMaximumSize(QtCore.QSize(451, 241))
        Dialog.setToolTip("")
        Dialog.setSizeGripEnabled(False)
        self.dateEdit_FROM = QtWidgets.QDateEdit(Dialog)
        self.dateEdit_FROM.setGeometry(QtCore.QRect(30, 90, 101, 21))
        self.dateEdit_FROM.setObjectName("dateEdit_FROM")
        self.comboBox_Cassa = QtWidgets.QComboBox(Dialog)
        self.comboBox_Cassa.setGeometry(QtCore.QRect(160, 40, 111, 22))
        self.comboBox_Cassa.setObjectName("comboBox_Cassa")
        self.comboBox_Filiale = QtWidgets.QComboBox(Dialog)
        self.comboBox_Filiale.setGeometry(QtCore.QRect(30, 40, 111, 22))
        self.comboBox_Filiale.setObjectName("comboBox_Filiale")
        self.dateEdit_TO = QtWidgets.QDateEdit(Dialog)
        self.dateEdit_TO.setGeometry(QtCore.QRect(160, 90, 110, 22))
        self.dateEdit_TO.setObjectName("dateEdit_TO")
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(340, 170, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.checkBox_PPOS = QtWidgets.QCheckBox(Dialog)
        self.checkBox_PPOS.setGeometry(QtCore.QRect(330, 30, 92, 23))
        self.checkBox_PPOS.setChecked(True)
        self.checkBox_PPOS.setObjectName("checkBox_PPOS")
        self.checkBox_OVG = QtWidgets.QCheckBox(Dialog)
        self.checkBox_OVG.setGeometry(QtCore.QRect(330, 60, 92, 23))
        self.checkBox_OVG.setChecked(True)
        self.checkBox_OVG.setObjectName("checkBox_OVG")
        self.checkBox_RTF = QtWidgets.QCheckBox(Dialog)
        self.checkBox_RTF.setGeometry(QtCore.QRect(330, 90, 111, 23))
        self.checkBox_RTF.setChecked(True)
        self.checkBox_RTF.setObjectName("checkBox_RTF")
        self.textEdit_OUT = QtWidgets.QTextEdit(Dialog)
        self.textEdit_OUT.setGeometry(QtCore.QRect(30, 130, 281, 91))
        self.textEdit_OUT.setObjectName("textEdit_OUT")
        self.label_Fil = QtWidgets.QLabel(Dialog)
        self.label_Fil.setGeometry(QtCore.QRect(30, 20, 67, 17))
        self.label_Fil.setObjectName("label_Fil")
        self.label_Cassa = QtWidgets.QLabel(Dialog)
        self.label_Cassa.setGeometry(QtCore.QRect(160, 20, 67, 17))
        self.label_Cassa.setObjectName("label_Cassa")
        self.label_Date = QtWidgets.QLabel(Dialog)
        self.label_Date.setGeometry(QtCore.QRect(30, 70, 241, 17))
        self.label_Date.setObjectName("label_Date")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

        ### IMPOSTO LA DATA ATTUALE ALLE FORM:
        self.dateEdit_FROM.setDateTime(QtCore.QDateTime.currentDateTime())
        self.dateEdit_TO.setDateTime(QtCore.QDateTime.currentDateTime())
        # CHIAMO LA FUNZIONE PER IL RECUPERO NUMERO CASSE:
        self.comboBox_Filiale.currentIndexChanged.connect(recuperoInfoCasse)
        # SE PREMO IL TASTO INZIO RECUPERO
        self.pushButton.clicked.connect(inizioRecupero)
        
    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.pushButton.setText(_translate("Dialog", "PushButton"))
        self.checkBox_PPOS.setText(_translate("Dialog", "PPOS"))
        self.checkBox_OVG.setText(_translate("Dialog", "Overgate"))
        self.checkBox_RTF.setText(_translate("Dialog", "FiscalPrinter"))
        self.label_Fil.setText(_translate("Dialog", "Filiale"))
        self.label_Cassa.setText(_translate("Dialog", "Cassa"))
        self.label_Date.setText(_translate("Dialog", "Data inizio:                Data fine:"))


if __name__ == "__main__":

    def recuperoInfoCasse(self):
        ui.comboBox_Cassa.clear()
        numfiliale = ui.comboBox_Filiale.currentText()
        ui.comboBox_Cassa.addItems(lr.recuperoNumeroCasse(numfiliale))


    def inizioRecupero(self):
        numerocassa = ui.comboBox_Cassa.currentText()
        numfiliale = ui.comboBox_Filiale.currentText()
        ip = lr.recuperoIndirizzo(numfiliale, numerocassa)
        connected = lr.connessioneCartellaCondivisa(ip)
        if not connected:
            ui.textEdit_OUT.setText("Non Connesso")
        else:
            ui.textEdit_OUT.setText("Connesso")
            controlloFlag(self)
        
        
    def controlloFlag(self):
        start = ui.dateEdit_FROM.date().toPyDate()
        end = ui.dateEdit_TO.date().toPyDate()
        
        print(start, end)
        if ui.checkBox_PPOS.isEnabled:
            print("ui.checkBox_PPOS.isEnabled:")
            lr.recuperoPPOS(r"/home/ml/Downloads/OvergateExportApp-main/", "", "", "" )
        if ui.checkBox_OVG.isEnabled:
            print("ui.checkBox_OVG.isEnabled:")
        if ui.checkBox_RTF.isEnabled:
            print("ui.checkBox_RTF.isEnabled:")


    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    lr = LogRetrieve()
    ui.setupUi(Dialog)
    ui.comboBox_Filiale.addItems(lr.recuperoFiliali())
    # ui.pushButton.setEnabled(False)
    Dialog.show()
    sys.exit(app.exec_())
