# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'OvergateExportApp.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.



from PyQt5 import QtCore, QtGui, QtWidgets

from LogRetrieve import LogRetrieve


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setWindowModality(QtCore.Qt.WindowModal)
        Dialog.setEnabled(True)
        Dialog.resize(317, 173)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        Dialog.setMinimumSize(QtCore.QSize(317, 173))
        Dialog.setMaximumSize(QtCore.QSize(317, 173))
        Dialog.setToolTip("")
        Dialog.setSizeGripEnabled(False)
        self.dateEditFrom = QtWidgets.QDateEdit(Dialog)
        self.dateEditFrom.setGeometry(QtCore.QRect(30, 70, 110, 22))
        self.dateEditFrom.setObjectName("dateEditFrom")
        self.comboBox_Cassa = QtWidgets.QComboBox(Dialog)
        self.comboBox_Cassa.setGeometry(QtCore.QRect(160, 30, 111, 22))
        self.comboBox_Cassa.setObjectName("comboBox_Cassa")
        self.comboBox_Filiale = QtWidgets.QComboBox(Dialog)
        self.comboBox_Filiale.setGeometry(QtCore.QRect(30, 30, 111, 22))
        self.comboBox_Filiale.setObjectName("comboBox_Filiale")
        self.dateEditTo = QtWidgets.QDateEdit(Dialog)
        self.dateEditTo.setGeometry(QtCore.QRect(160, 70, 110, 22))
        self.dateEditTo.setObjectName("dateEditTo")
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(120, 120, 75, 23))
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

        ### IMPOSTO LA DATA ATTUALE ALLE FORM:
        self.dateEditFrom.setDateTime(QtCore.QDateTime.currentDateTime())
        self.dateEditTo.setDateTime(QtCore.QDateTime.currentDateTime())
        # CHIAMO LA FUNZIONE PER IL RECUPERO NUMERO CASSE:
        self.comboBox_Filiale.currentIndexChanged.connect(self.recuperoInfoCasse)
        # SE PREMO IL TASTO RECUPERO L'INDIRIZZO IP:
        self.pushButton.clicked.connect(self.inizioRecupero)
        

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.pushButton.setText(_translate("Dialog", "PushButton"))


    def recuperoInfoCasse(self):
        self.comboBox_Cassa.clear()
        numfiliale = self.comboBox_Filiale.currentText()
        self.comboBox_Cassa.addItems(lr.recuperoNumeroCasse(numfiliale))

    def inizioRecupero(self):
        numerocassa = self.comboBox_Cassa.currentText()
        numfiliale = self.comboBox_Filiale.currentText()
        lr.recuperoIndirizzo(numfiliale, numerocassa)


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    lr = LogRetrieve()
    ui.setupUi(Dialog)
    ui.comboBox_Filiale.addItems(lr.recuperoFiliali())
    # numfiliale = ui.comboBox_Filiale.currentText()
    # ui.pushButton.setEnabled(False)
    Dialog.show()
    sys.exit(app.exec_())



  